### PR TITLE
Marketing Website

### PR DESCRIPTION
**Pull request by alexelash**
# Overview
Adds a new marketing site for DistrictBuilder that replaces the splash page.

# Demo
Homepage (with Subscribe banner)
Screen Shot 2020-09-08 at 3 58 03 PM

Feature section
Screen Shot 2020-09-08 at 4 02 28 PM

Resources section
Screen Shot 2020-09-08 at 4 02 35 PM

# Notes
- We have two articles in the screenshots, but I'll add a third if we get one in time for launch.
- Once we launch this, we'll need to let Karissa know so she can test GTM.

# Testing
- `git pull`
- Confirm that you are dropped into the page in the screenshots as opposed to the splash page
- Test all links and buttons
- Go to http://localhost:4000/wrong to see the 404 page
- Check the Contact page
- Cross-browser test

### CODE REVIEW

**Comment by alexelash** [comment]
Links to the new product feature roadmap in the banner, and adds a note in the features section doing the same.

**Comment by tgilcrest** [comment]
Any chance we can make the roadmap banner say "We're making..." instead of "We plan to make..."?

**Comment by alexelash** [comment]
@tgilcrest Yep! Will do in my next commit.

**Comment by alexelash** [comment]
Added the Public Mapping Project book to resources:
Screen Shot 2020-09-17 at 7 09 44 PM

**Comment by alexelash** [comment]
@jfrankl I think this is ready to review. If we have changes from now till launch, they'll probably be text adjustments.

**Review by jfrankl — COMMENTED** [review]
Absolutely stunning website. Thank you for all of the thought and attention you've put into this project—it really shines.

I have a few issues and comments:

Looks like there is supposed to be a logo showing up here but it doesn't show up for me
Screen Shot 2020-09-21 at 2 28 45 PM

To my eye, the "Delve deeper" text looks too close to the header underneath, and it's closer than similar text in other sections
Screen Shot 2020-09-21 at 2 27 44 PM
vs
Screen Shot 2020-09-21 at 2 27 11 PM

The text in the features section looks small to me and I struggled to read it, which doesn't happen to me often. Freight seems to render smaller than the size indicates, but it's only an issue for me in this section. I think bumping up the size a level would help. 
Screen Shot 2020-09-21 at 2 27 16 PM

This header text gets lost for me on top of the white book. 
Screen Shot 2020-09-21 at 2 28 04 PM

**Comment by rajadain** [comment]
In some widths, there is a hairline visible between the rectangular image and the crossover pattern in Firefox:

image

If I resize the browser, for some widths it disappears.

**Comment by alexelash** [comment]
@jfrankl thanks for the feedback! 

## Contact
I changed up the size of the text on the Contact page. To your point about readibility on the image, I added a text shadow and darkened the gradient overtop so it's got more contrast.
Screen Shot 2020-09-23 at 10 28 52 AM


## Featured section
Body copy for each feature is a size bigger. I also added the "soon" indicator to the share feature block, and moved it to the third position. It's just waiting on final text from Stacy and Karissa. 
fyi @tgilcrest
Screen Shot 2020-09-23 at 2 16 17 PM

@rajadain Good eye. This was something I'd noticed earlier and forgotten to fix (just needed a bit of overlap).

**Review by jfrankl — APPROVED** [review]
Excellent work.

**Pull request merged**
